INHERIT: active-handout.yml

site_name: MLOps & Interviews

extra:
  custom_variables:
    repo_aps: https://github.com/insper/mlops
    repo_aps_git: https://github.com/insper/mlops.git

extra_javascript:
  - js/tabs.js
  - js/termynal.js
  - js/custom.js

extra_css:
    - css/termynal.css

nav:
  - 'Home': index.md
  - about.md
  - deadlines.md
  - Content:
    - "01 - Introduction":
      - modules/01-intro/intro.md
      - modules/01-intro/aps01.md
    - "02 - Deploy: first try!":
      - modules/02-api/api_deploy.md
    - "03 - Batch prediction":
      - "Part 1":
        - modules/03-batch/intro.md
        - modules/03-batch/data_formats.md
        - modules/03-batch/practicing.md
      - "Part 2":
        - modules/03-batch/sql.md
        - modules/03-batch/db_tool.md
        - modules/03-batch/dot_env.md
        - modules/03-batch/aps02_sql.md
    - "04 - Interview 01":
      - modules/04-int01/faq.md
      - modules/04-int01/int01.md
    - "05 - Docker":
      - modules/05-docker/intro.md
      - modules/05-docker/s3.md
      - modules/05-docker/docker.md
    - "06 - Message Broker":
      - modules/06-message-broker/intro.md
      - modules/06-message-broker/rabbitmq.md
