INHERIT: active-handout.yml

site_name: MLOps & Interviews



extra:
  custom_variables:
    repo_aps: https://github.com/insper/mlops
    repo_aps_git: https://github.com/insper/mlops.git

extra_javascript:
  - js/tabs.js
  - js/termynal.js
  - js/custom.js

extra_css:
    - css/termynal.css

nav:
  - 'Home': index.md
  - about.md
  - deadlines.md
  - contributions.md
  - project/project.md
  - Content:
    - "01 - Introduction":
      - modules/01-intro/intro.md
      - modules/01-intro/aps01.md
    - "02 - Deploy: first try!":
      - modules/02-api/api_deploy.md
    - "03 - Batch prediction":
      - "Part 1":
        - modules/03-batch/intro.md
        - modules/03-batch/data_formats.md
        - modules/03-batch/practicing.md
      - "Part 2":
        - modules/03-batch/sql.md
        - modules/03-batch/db_tool.md
        - modules/03-batch/dot_env.md
        - modules/03-batch/aps02_sql.md
    - "04 - Interview 01":
      - modules/04-int01/faq.md
      - modules/04-int01/int01.md
    - "05 - Docker":
      - modules/05-docker/intro.md
      - modules/05-docker/s3.md
      - modules/05-docker/docker.md
    - "06 - Message Broker":
      - modules/06-message-broker/intro.md
      - modules/06-message-broker/rabbitmq.md
    - "07 - Lambda Functions":
      - "Part 1":
        - modules/07-lambda/aws_lambda.md
        - modules/07-lambda/lambda_practicing.md
        - modules/07-lambda/api_gateway.md
      - "Part 2":
        - modules/07-lambda/sentiment_analysis.md
        - modules/07-lambda/sa_lambda_function.md
        - modules/07-lambda/lambda_layer.md
      - "Part 3":
        - modules/07-lambda/lambda_quotas.md
        - modules/07-lambda/lambda_and_docker.md
        - modules/07-lambda/aps03_lambda.md
    - "08 - Queues":
      - modules/08-queue/intro.md
      - modules/08-queue/concurrent_execution.md
      - modules/08-queue/sqs_practicing.md
      - modules/08-queue/sqs_and_lambda.md
    - "09 - Interview 02":
      - modules/09-int02/int02.md
    - "10 - Documentation":
      - modules/10-documentation/intro.md
      - modules/10-documentation/code_documentation.md
      - modules/10-documentation/fast_api_docs.md
      - modules/10-documentation/ml_canvas.md
    - "11 - Logging":
      - modules/11-logging/intro.md
      - modules/11-logging/python_logging.md
      - modules/11-logging/read_aws_logs.md
      - modules/11-logging/write_logs_to_s3.md
    - "12 - CI/CD":
      - modules/12-ci-cd/intro.md
      - modules/12-ci-cd/testing.md
      - modules/12-ci-cd/auto_deploy.md
    - "13 - Tracking":
      - "Part 1":
        - modules/13-tracking/intro.md
        - modules/13-tracking/mlflow.md
      - "Part 2":
        - modules/13-tracking/centralization.md
        - modules/13-tracking/model_registry.md
    - "14 - Interview 03":
      - modules/14-int03/int03.md
    - "15 - Monitoring":
      - "Part 1":
        - modules/15-monitoring/intro.md
        - modules/15-monitoring/metrics.md
        - modules/15-monitoring/model_degradation.md
        - modules/15-monitoring/data_drift_methods.md
      - "Part 2":
        - modules/15-monitoring/data_drift_ml.md
        - modules/15-monitoring/performance_degradation.md
    - "16 - Data versioning":
      - modules/16-data-versioning/intro.md
      - modules/16-data-versioning/dvc.md
      - modules/16-data-versioning/s3_storage.md